name: Generate Release Note

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate release note
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
